const constants = {
    SERVER_ERROR:"Server error",
    NO_USERS: "No users available",
    USER_NOT_FOUND:"User not found",
    STUDENT_NOT_FOUND:"Student not found",
    STUDENTS_NOT_FOUND:"students not found",
    COURSES_NOT_FOUND:"courses not found",
    CLASS_NOT_FOUND:"Class not found",
    VERIFIED_TEACHER_ONLY:"Only verified teachers can create a course.  Wait for your verification!",
    UNAUTHORISED:"Unauthorized. Please log in.",
    NO_COURSE_FOUND:"no course found",
    PDF_REQUIRED:"PDF file is required",
    MODULE_NOT_FOUND:"Module not found",
    ASSIGNMENT_NOT_FOUND:"Assignment not found",
    NO_QUIZ_FOR_COURSE:"No quizzes found for this course.",
    QUIZ_NOT_FOUND:"Quiz not found.",
    FAILED_TO_DELETE_QUIZ:"Failed to delete quiz.",
    COURSE_OR_STUDENT_NOT_FOUND:"Course or student not found",
    ASSIGNMENT_DUE_PASSED:"The assignment due date has passed. You cannot submit the assignment.",
    FILE_IS_REQUIRED:"File is required for submission",
    CLASSES_NOT_FOUND:"No classes found",
    ALL_FIELD_REQUIRED_CLASS:"All fields are required to create a class.",
    NOTIFICATION_NOT_UPDATED:"No notifications were updated",
    INVALID_COURSEID:"Invalid course ID",
    INVALID_MODULEID:"Invalid module ID",
    INVALID_PHONE:"Invalid phone number format",
    INVALID_OTP: "Invalid OTP",
    USER_EXISTS: "User already exists!",
    ENTER_VALID_OTP: "Enter valid OTP",
    OTP_EXPIRED: "OTP has expired",
    VERIFY_EMAIL_BEFORE_LOGIN: "Please verify your email before logging in",
    INVALID_DETAILS: "Invalid details",
    ACCOUNT_BLOCKED: "Your profile has been blocked!",
    MISSING_FIELDS: "Missing required fields",
    PASSWORD_AND_CONFIRM_MISMATCH: "Password and confirm password should be same!",
    TOKEN_EXPIRED: "Token is invalid or has expired",
    WRONG_PASSWORD: "Wrong password!",

}

module.exports = constants
